apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
data:
  DB_USERNAME: "myuser"
  DB_NAME: "mydatabase"
  DB_HOST: "udacity-project-postgresql"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: env-secret
type: Opaque
data:
  DB_PASSWORD: qaQutUZ9Of